apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helmbasic-develop
  namespace: staging
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: helmbasic-stagging
  chart:
    git: git@github.com:e-raug/helmflux
    path: helmbasics
    ref: develop
  values:
    environment: development
    replicaCount: 1
    ingress:
      host: mywebserver.dev.kubesandclouds.com
    image:
      repository: nginx
      tag: latest

